# Generated by Django 3.2.8 on 2021-10-21 11:22

import democ_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(default=democ_api.models.genepk, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('quote_id', models.IntegerField(default=democ_api.models.genepk, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('premium', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('cover', models.IntegerField()),
                ('state', models.CharField(default='new', max_length=10)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
